### PR TITLE
Fixed typo in readme

### PR DESCRIPTION
**Pull request by vlazzle**
vandroid -> android

### CODE REVIEW

**Comment by vlazzle** [comment]
> Thanks, your CLA has been submitted.

I signed the CLA.

**Comment by dandv** [comment]
This has been fixed and can be closed. Thanks!

**Review by melashkov — APPROVED** [review]

**Comment by vlazzle** [comment]
This is already fixed on master, and the fix happens to be the merge conflict, so my fix isn't needed.

**Comment by kengraWin** [comment]
good

**Pull request closed without merging**
